# Generated by Django 5.0.3 on 2024-03-18 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="pub_date",
            new_name="date",
        ),
    ]
