# Generated by Django 5.0.3 on 2024-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_pub_date_blog_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="body",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
    ]
